name:                typescript-types
version:             0.1.0.0
github:              "mstksg/typescript-types"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "2020 Justin Le"

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Werror=incomplete-patterns
- -Wcompat
- -Wredundant-constraints

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub.

dependencies:
- base >= 4.7 && < 5
- text
- containers
- scientific
- functor-combinators >= 0.3.5.1
- recursion-schemes
- aeson
- dependent-sum
- some
- sop-core
- vector
- prettyprinter >= 1.7
- fin
- vec
- aeson-better-errors
- transformers


library:
  source-dirs: src

# executables:
#   typescript-json-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - typescript-json

# tests:
#   typescript-json-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - typescript-json
